from typing import Dict, List, Tuple, Union

Headers = List[Tuple[bytes, bytes]]
DynamicTable = Dict[str, Union[int, Headers]]

class DecompressionFailed(Exception): ...
class DecoderStreamError(Exception): ...
class EncoderStreamError(Exception): ...
class StreamBlocked(Exception): ...

class Decoder:
    def __init__(self, max_table_capacity: int, blocked_streams: int) -> None: ...
    def feed_encoder(self, data: bytes) -> List[int]: ...
    def feed_header(self, stream_id: int, data: bytes) -> Tuple[bytes, Headers]: ...
    def resume_header(self, stream_id: int) -> Tuple[bytes, Headers]: ...
    def get_dynamic_table(self) -> DynamicTable: ...

class Encoder:
    def apply_settings(
        self, max_table_capacity: int, blocked_streams: int
    ) -> bytes: ...
    def encode(self, stream_id: int, headers: Headers) -> Tuple[bytes, bytes]: ...
    def feed_decoder(self, data: bytes) -> None: ...
    def get_dynamic_table(self) -> DynamicTable: ...
